/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;
import Models.Alumno;
import Controllers.Alumnos;
import Reportes.Reportes;
import Views.SeleccionarAlumno;
import conexion.Conexion;
import java.awt.Event;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormatSymbols;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import static proyectomp.EMPLEADOSS_CREAR.txtNombre;
import static proyectomp.LOCAL_REGISTRO.tblLocal;
import static proyectomp.MostrarVentas.tblMostrarVenta;

/**
 *
 * @author Calix
 */
public class VENTA extends javax.swing.JFrame {
    TableRowSorter trs;
     private static conexion.Conexion con = new Conexion();
    private static Connection conexion = con.getConexion();
    private  static PreparedStatement ps = null;

    /**
     * Creates new form VENTA
     */
    public VENTA() {
        initComponents();
        tblProductos.setSelectionMode(NORMAL);
        tblDetalle.setSelectionMode(NORMAL);
         InputMap map2 = TXTnombre.getInputMap(JTextField.WHEN_FOCUSED); 
    map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap maps = txtBuscar.getInputMap(JTextField.WHEN_FOCUSED); 
    maps.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap map3 = txtGrado.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap ma1 = txtPrecio.getInputMap(JTextField.WHEN_FOCUSED); 
    ma1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        tblProductos.getTableHeader().setReorderingAllowed(false);
        Funciones.setListarProductos("");
        txtFactura.setText(Funciones.extraerNumerofactura());
        this.setExtendedState(MAXIMIZED_BOTH);
        lblCount.setText(Funciones.extraerRangoMaximo());
        txtISV.setText(Funciones.extraerImpuesto());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnGeneral = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtISV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtResu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtGravado = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblCount = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JFormattedTextField();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtMes = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("VENTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 11, 130, -1));

        jLabel2.setText("Identidad del Alumno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        TXTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreActionPerformed(evt);
            }
        });
        TXTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnombreKeyTyped(evt);
            }
        });
        jPanel1.add(TXTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 166, -1));

        jLabel4.setText("Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        txtGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradoActionPerformed(evt);
            }
        });
        txtGrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGradoKeyTyped(evt);
            }
        });
        jPanel1.add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 166, -1));

        jLabel5.setText("Grado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, -1));

        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 60, 20));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Modalidad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setRowHeight(30);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 727, 176));

        txtBuscar.setNextFocusableComponent(txtPrecio);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 154, -1));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modalidad", "Grado", "Mensualidades", "Precio", "Total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.setRowHeight(30);
        jScrollPane4.setViewportView(tblDetalle);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 336, 727, 222));

        btnGeneral.setText("GENERAR VENTA");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 601, 180, 69));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("GRAVADO");

        sub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sub.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ISV");

        txtISV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtISV.setText("0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("TOTAL");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("L");

        txtResu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResu.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nro FACTURA");

        txtFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFactura.setText("123-4553-2333");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("SUB TOTAL");

        TxtGravado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtGravado.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISV, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txtFactura))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFactura))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtResu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 11, 330, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("VENTA DEL PRODUCTO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 60));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, -1));

        lblCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 0, 51));
        lblCount.setText("ewewe");
        jPanel1.add(lblCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 601, 446, 40));

        try {
            txtIdentidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIdentidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIdentidad.setNextFocusableComponent(TXTnombre);
        txtIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentidadActionPerformed(evt);
            }
        });
        txtIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyPressed(evt);
            }
        });
        jPanel1.add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 166, -1));

        btnDelete.setText("X");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 535, -1, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 47, 22, -1));

        jLabel13.setText("Mensualidad A Pagar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 166, -1));

        txtMes.setDateFormatString("yyyy-MM-dd ");
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 210, -1));

        jLabel16.setText("Alumno");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1330, 770));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int a = 0;
    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
       double acumulador=0;
        if(txtIdentidad.getText().equals("    -    ")|| 
                this.TXTnombre.getText().length()==0||
                this.tblDetalle.getRowCount()==0||
                this.txtGrado.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Debe Ingresar Todos Los Datos", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
               }else{
           
                   int fila = tblDetalle.getSelectedRow();
        
        Sentencias s = new Sentencias();
            
            
             Sentencias_Angel sa= new Sentencias_Angel();
                         
            sa.setTelefono_CL(txtIdentidad.getText());           
                
                     if(Venta()){
                     String d = Funciones.extraerIdMaxSAR();
                     sa.setNum_Factura(txtFactura.getText());
                     sa.setId_Sar(Integer.parseInt(d));
                     Funciones_Angel.isUpdateSar(sa);
                     obtener();
                     limpiar();
                     }
                    
        }
           
     
      
    
    }//GEN-LAST:event_btnGeneralActionPerformed

    private boolean Venta(){
        String fechaa = null;
        java.util.Date fecha = new java.util.Date();
               SimpleDateFormat formato = new SimpleDateFormat("yyy-MM-dd");
               fechaa = formato.format(fecha);
        Sentencias s = new Sentencias();   
        s.setFecha_VV(fechaa);
        String facturas = Funciones.extraerNumerofactura();
        s.setNo_Factura_VV(facturas);
        s.setTelefon_CL(this.txtIdentidad.getText());
        s.setTotal(Double.parseDouble(txtResu.getText()));
        s.setSar(Integer.parseInt(Funciones_Henry.extraerIdMaxSAR()));
        s.setImpuestogravado(Double.parseDouble(TxtGravado.getText()));
        if(Funciones.isRegisterVenta(s)){
            return true;
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo Realizar la venta, consulte con el administrador de sistema.");
            return false;
        }
    }
    
    
    private void obtener(){
        String idd = Funciones.extraerVentaMax();
        Sentencias s = new Sentencias();
        
        for(int i=0; i< tblDetalle.getRowCount(); i++){
        Funciones.isRegisterDetalle_Pago(Integer.parseInt(tblDetalle.getValueAt(i, 4).toString()),
                Integer.parseInt(Funciones.extraerVentaMax())
                , tblDetalle.getValueAt(i, 3).toString(), 
                Integer.parseInt(tblDetalle.getValueAt(i, 0).toString()),
                tblDetalle.getValueAt(i, 6).toString()); 
        
    }
    }
    
    
    
    int count =0;
    int condicion = 0;
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if (txtMes.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una mensualidad");
            return;
        }
        
        if (txtGrado.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "El valor deber ser distinto a cero");
            return;
            
        }
        
        if (txtPrecio.getText().equals("0")) {
            JOptionPane.showMessageDialog(rootPane, "Debe Ingresar un Precio");
            txtPrecio.requestFocus();
        }
        
        if (txtPrecio.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe Ingresar un Precio");
            txtPrecio.requestFocus();
        }
        else{
      
        int fila = tblProductos.getSelectedRow(); 
              int cero = 0;
       count++;
        if (evt.getClickCount() == 2) {
            int a =0;

           String Modalidad, grado, precio, Mensualidad, total, Mes, idProducto;
           DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
           Modalidad= tblProductos.getValueAt(fila, 1).toString();
           idProducto= tblProductos.getValueAt(fila, 0).toString();
           grado= txtGrado.getText();
           precio= txtPrecio.getText();
           Mes = ((JTextField) this.txtMes.getDateEditor().getUiComponent()).getText();
            Calendar calendar = Calendar.getInstance();
                    calendar.setTime(txtMes.getDate());

                    // Obtener el mes (tener en cuenta que los meses en Calendar van de 0 a 11)
                    int mesNumber = calendar.get(Calendar.MONTH);
                    String nombreMes = obtenerNombreMes(mesNumber);
           Mensualidad = "1";
            
           DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
            
           
           
           double suma = Double.parseDouble(precio)* Double.parseDouble(Mensualidad);
           String resultado = String.valueOf(suma);
           
           
           
           String filla[] = {idProducto,Modalidad, grado, nombreMes, precio, resultado, Mes};
           m.addRow(filla);
           suma();
       
            
        }
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private String obtenerNombreMes(int numeroMes) {
        DateFormatSymbols dfs = new DateFormatSymbols();
        String[] nombresMeses = dfs.getMonths();

        // Devuelve el nombre del mes correspondiente al número proporcionado
        return nombresMeses[numeroMes];
    }
    
    private void suma(){
        DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
        double valor = 0;
        double total = 0;
        double isv=0;
        double gravado=0;
        
        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            double dato = Double.parseDouble(tblDetalle.getValueAt(i, 5).toString());
            if (!Controllers.Consultas_Catalogo.PruductoValidateImpuesto(tblDetalle.getValueAt(i, 0).toString())) {
                double isvcalculo= dato * (Double.parseDouble(Funciones.extraerImpuesto()));
                isv +=isvcalculo;
                gravado+=dato;
            }
            total +=dato;    
        }     
          BigDecimal subtotal = new BigDecimal(total);
          subtotal = subtotal.setScale(2, RoundingMode.HALF_UP);
          sub.setText(String.valueOf(subtotal)); //Total sin Impuesto
          TxtGravado.setText(String.valueOf(gravado));
          txtResu.setText(String.valueOf(total+isv)); //Total con Impuesto
          
          txtISV.setText(String.valueOf(isv)); //total ISV
    }
    private void limpiar(){
        
        try {
            Reportes reporte = new Reportes();
             HashMap datos = new HashMap();
             datos.put("pa_id", Funciones.extraerVentaMax());
             reporte.ReporteVenta(datos);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch(SQLException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         DefaultTableModel modelo = (DefaultTableModel)tblDetalle.getModel();
            
            //modelo.fireTableDataChanged();
 
            
            while(modelo.getRowCount() > 0 ){
                modelo.removeRow(0);
                
            }
            txtIdentidad.setText(null);
            TXTnombre.setText(null);
            txtApellido.setText(null);
            txtGrado.setText(null);
            txtISV.setText(null);
            sub.setText(null);
            txtPrecio.setText(null);
            txtResu.setText(null);
            lblCount.setText(Funciones.extraerRangoMaximo());
            txtMes.setDate(null);
            TxtGravado.setText(null);
           // Funciones.extraerRangoMaximo();
            txtFactura.setText(Funciones.extraerNumerofactura());
            
            
      
           
    }
    private void TXTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreActionPerformed

    private void txtGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradoActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
txtBuscar.setText(txtBuscar.getText().replaceAll("( )+", " "));
        Validaciones.Space(txtBuscar.getText().length(), evt);        DefaultTableModel m = (DefaultTableModel) tblProductos.getModel();
        txtBuscar.addKeyListener(new KeyAdapter() { 

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 1));
                
                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }
        
        
        });
        trs = new TableRowSorter(m);
        tblProductos.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void TXTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnombreKeyTyped
JTextField txtnombre = (JTextField)evt.getComponent();

String texto=txtnombre.getText();//.trim();//para evitar espacios en blanco antes y despues del texto
if(texto.length()>0){
char primero=texto.charAt(0);
texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
txtnombre.setText(texto);
}
TXTnombre.setText(TXTnombre.getText().replaceAll("( )+", " "));
        Validaciones.Space(TXTnombre.getText().length(), evt);
        char l = evt.getKeyChar();
         
        if(Character.isDigit(l)){
            getToolkit().beep();
            evt.consume();
        }
       
            int tam = TXTnombre.getText().length();
        if(tam>=30){
            evt.consume();
        }  
    
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreKeyTyped

    private void txtGradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoKeyTyped
JTextField txtnombre = (JTextField)evt.getComponent();

String texto=txtnombre.getText();//.trim();//para evitar espacios en blanco antes y despues del texto
if(texto.length()>0){
char primero=texto.charAt(0);
texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
txtnombre.setText(texto);
}
txtGrado.setText(txtGrado.getText().replaceAll("( )+", " "));
        Validaciones.Space(txtGrado.getText().length(), evt);
        char l = evt.getKeyChar();
         
        if(Character.isDigit(l)){
            getToolkit().beep();
            evt.consume();
        }
       
            int tam = txtGrado.getText().length();
        if(tam>=30){
            evt.consume();
        }  
    
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtGradoKeyTyped

    private void txtIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentidadActionPerformed
        Alumno alumno = new Alumno();
        alumno.setIdentidad(txtIdentidad.getText());
        Alumnos.setListarAlumnos(alumno);
        if (alumno!=null) {
            txtPrecio.setText(String.valueOf(alumno.getValorMensualidad()));
            TXTnombre.setText(alumno.getNombres());
            txtApellido.setText(alumno.getApellidos());
            txtGrado.setText(alumno.getGrado());
        }else{
            JOptionPane.showMessageDialog(null, "Este estudiante no se encuentra registrado");
        }
    }//GEN-LAST:event_txtIdentidadActionPerformed

    private void txtIdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyPressed

    }//GEN-LAST:event_txtIdentidadKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int fila = tblDetalle.getSelectedRow();
       DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
        m.removeRow(fila);
        suma();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Views.SeleccionarAlumno seleccionarAlumno = new SeleccionarAlumno();
        seleccionarAlumno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtPrecio.getText().length();
        if(tam>=6){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void validar(){
               
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField TXTnombre;
    private javax.swing.JLabel TxtGravado;
    private javax.swing.JButton btnDelete;
    public static javax.swing.JButton btnGeneral;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel sub;
    private javax.swing.JTable tblDetalle;
    public static javax.swing.JTable tblProductos;
    public static javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtFactura;
    public static javax.swing.JTextField txtGrado;
    private javax.swing.JLabel txtISV;
    public static javax.swing.JFormattedTextField txtIdentidad;
    private com.toedter.calendar.JDateChooser txtMes;
    public static javax.swing.JTextField txtPrecio;
    private javax.swing.JLabel txtResu;
    // End of variables declaration//GEN-END:variables
}
