/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.Seguridad;
import Models.Usuario;
import Reportes.Reportes;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import proyectomp.Funciones;

/**
 *
 * @author Irving Calix
 */
public class Bitacora extends javax.swing.JPanel {

    /**
     * Creates new form MostrarFacturas
     */
    public Bitacora() {
        initComponents();
        Controllers.Seguridad.setListarBitacoraFlexible(null,null,null);
        	
        //this.tblBitacora.setDefaultRenderer(Object.class, new Renderizado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBitacora = new javax.swing.JTable();
        txtModulo = new javax.swing.JTextField();
        alumno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_accion", "Accion", "Modulo", "Usuario", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBitacoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBitacora);
        if (tblBitacora.getColumnModel().getColumnCount() > 0) {
            tblBitacora.getColumnModel().getColumn(0).setResizable(false);
            tblBitacora.getColumnModel().getColumn(2).setResizable(false);
            tblBitacora.getColumnModel().getColumn(3).setResizable(false);
            tblBitacora.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1110, 490));

        txtModulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModuloKeyReleased(evt);
            }
        });
        add(txtModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 240, -1));

        alumno.setBackground(new java.awt.Color(0, 0, 0));
        alumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alumno.setText("Modulo");
        add(alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void txtModuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModuloKeyReleased
        Controllers.Seguridad.setListarBitacoraFlexible(null,null,txtModulo.getText());
    }//GEN-LAST:event_txtModuloKeyReleased

    private void tblBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBitacoraMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tblBitacora.getSelectedRow(); 
            String id = tblBitacora.getValueAt(fila, 0).toString();
            
             try {
            Reportes reporte = new Reportes();
             HashMap datos = new HashMap();
             datos.put("pa_id", id);
             reporte.ReporteVenta(datos);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
             catch(SQLException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_tblBitacoraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblBitacora;
    private javax.swing.JTextField txtModulo;
    // End of variables declaration//GEN-END:variables
}
