/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Reportes.Reportes;
import static Views.MostrarFacturas.tblPagos;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Irving Calix
 */
public class Cobranza extends javax.swing.JPanel {

    /**
     * Creates new form Cobranza
     */
    public Cobranza() {
        initComponents();
        Controllers.Alumnos.setListarAlumnosPorEstado("",java.time.LocalDate.now().getYear(), java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alumno", "Identidad", "Grado", "Encargado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPagosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 55, 1080, 570));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });
        add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 21, 169, -1));

        jLabel1.setText("Estudiante");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Estudiantes sin Pagar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 27, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        Controllers.Alumnos.setListarAlumnosPorEstado(txt_nombre.getText(),java.time.LocalDate.now().getYear(), java.time.LocalDate.now().toString());
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void tblPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPagosMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tblPagos.getSelectedRow(); 
            String Alumno = tblPagos.getValueAt(fila, 0).toString();
            String Cliente = tblPagos.getValueAt(fila, 3).toString();
            String identidad = tblPagos.getValueAt(fila, 1).toString();
            String anio = String.valueOf(java.time.LocalDate.now().getYear());
            
             try {
            Reportes reporte = new Reportes();
             HashMap datos = new HashMap();
             datos.put("pa_alumno", identidad);
             datos.put("pa_anio", anio);
             datos.put("pa_cliente", Cliente);
             datos.put("pa_name_alumno", Alumno);
             
             reporte.ReporteCobranza(datos);
        } catch (JRException ex) {
                 JOptionPane.showMessageDialog(null, "Error en la conexión a la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                   ex.printStackTrace();
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
             catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al generar el reporte Jasper: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_tblPagosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblPagos;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
