/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Alumnos;
import proyectomp.*;
import Models.Encargados;
import javax.swing.DefaultComboBoxModel;
import Models.Alumno;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Irving Calix
 */
public class Matricula extends javax.swing.JFrame {
    /**
     
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
        DefaultComboBoxModel<Encargados> comboBoxModel = Alumnos.CargarEncargados();
        jcbEncargado.setModel(comboBoxModel);
        llenarGrado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdentidad = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Encargado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jcbEncargado = new javax.swing.JComboBox<>();
        txtMensualidad = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        grado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            txtIdentidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 300, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRES:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GRADO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("V.MATRICULA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, -1, 20));

        Encargado.setBackground(new java.awt.Color(255, 255, 255));
        Encargado.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Encargado.setForeground(new java.awt.Color(255, 255, 255));
        Encargado.setText("ENCARGADO:");
        jPanel1.add(Encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V.MENSUALIDAD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, 20));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 300, -1));
        jPanel1.add(jcbEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 300, -1));
        jPanel1.add(txtMensualidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 300, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 300, -1));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 300, -1));

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("FECHA:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, 20));
        jPanel1.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 300, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 120, 40));

        grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hoho", "hehe", "ha" }));
        jPanel1.add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 290, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IDENTIDAD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 20));

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1280, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarGrado(){
        DefaultComboBoxModel<String> gradocombo = new DefaultComboBoxModel<>();
        gradocombo.addElement("Primer Grado Pre-Basica");
        gradocombo.addElement("Segundo Grado Pre-Basica");
        gradocombo.addElement("Tercer Grado Pre-Basica");
        gradocombo.addElement("Primer Grado Basica");
        gradocombo.addElement("Segundo Grado Basica");
        gradocombo.addElement("Tercero Grado Basica");
        gradocombo.addElement("Cuarto Grado Basica");
        gradocombo.addElement("Quinto Grado Basica");
        gradocombo.addElement("Sexto Grado Basica");
        gradocombo.addElement("Septimo Grado Basica");
        gradocombo.addElement("Octavo Grado Basica");
        gradocombo.addElement("Noveno Grado Basica");
        grado.setModel(gradocombo);
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Encargados encargadoselect = (Encargados) jcbEncargado.getSelectedItem();
        Alumno alumno = new Alumno();
        alumno.setIdentidad(txtIdentidad.getText());
        alumno.setNombres(txtNombres.getText());
        alumno.setApellidos(txtApellidos.getText());
        alumno.setIdCliente(encargadoselect.getId());
        alumno.setGrado(grado.getSelectedItem().toString());
        alumno.setValorMatricula(Integer.parseInt(txtMatricula.getText()));
        alumno.setValorMensualidad(Integer.parseInt(txtMensualidad.getText()));
        alumno.setFechaMatricula(((JTextField)this.dateFecha.getDateEditor().getUiComponent()).getText());
        
        if (Alumnos.isRegisterAlumno(alumno)) {
            JOptionPane.showMessageDialog(null, "Estudiante registrado exitosamente");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encargado;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox<Encargados> jcbEncargado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JFormattedTextField txtIdentidad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMensualidad;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
